AOS.init({duration:1000,once:!0,offset:100});if(typeof lucide!=="undefined"&&lucide.createIcons)lucide.createIcons();document.addEventListener("DOMContentLoaded",()=>{const mobileMenuBtn=document.getElementById("mobile-menu-button");const closeMenuBtn=document.getElementById("close-menu-button");const mobileMenu=document.getElementById("mobile-menu");if(mobileMenuBtn&&closeMenuBtn&&mobileMenu){mobileMenuBtn.addEventListener("click",()=>mobileMenu.classList.add("active"));closeMenuBtn.addEventListener("click",()=>mobileMenu.classList.remove("active"));mobileMenu.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>mobileMenu.classList.remove("active")))}
document.querySelectorAll('a[href^="#"]').forEach(anchor=>{anchor.addEventListener("click",e=>{const href=anchor.getAttribute("href");if(!href||href==="#")return;const target=document.querySelector(href);if(!target)return;e.preventDefault();target.scrollIntoView({behavior:"smooth"})})});const header=document.getElementById("main-header");if(header){window.addEventListener("scroll",()=>{header.classList.toggle("sticky-nav-scrolled",window.scrollY>50)})}
const marqueeRow=document.getElementById("marquee-content-original");const marqueeClone=document.getElementById("marquee-content-clone");function updateMarqueeClone(){if(window.innerWidth>768){if(marqueeRow&&marqueeClone)marqueeClone.innerHTML=marqueeRow.innerHTML}else{if(marqueeClone)marqueeClone.innerHTML=""}}
updateMarqueeClone();window.addEventListener("resize",updateMarqueeClone);const style=document.createElement("style");style.innerHTML=`
    @keyframes scrollMarquee {
      0% { transform: translateX(0); }
      100% { transform: translateX(-50%); }
    }
    .marquee-container-boxes {
      overflow: hidden;
      white-space: nowrap;
      display: flex;
      cursor: grab;
    }
    .marquee-container-boxes.grabbing {
      cursor: grabbing;
    }
    .marquee-boxes-row {
      display: flex;
      gap: 2rem;
      animation: scrollMarquee 40s linear infinite;
    }
  `;document.head.appendChild(style);const marqueeContainer=document.querySelector(".marquee-container-boxes");if(marqueeContainer){let isDown=!1,startX,scrollLeft;marqueeContainer.addEventListener("mousedown",e=>{isDown=!0;marqueeContainer.classList.add("grabbing");startX=e.pageX-marqueeContainer.offsetLeft;scrollLeft=marqueeContainer.scrollLeft});marqueeContainer.addEventListener("mouseleave",()=>{isDown=!1;marqueeContainer.classList.remove("grabbing")});marqueeContainer.addEventListener("mouseup",()=>{isDown=!1;marqueeContainer.classList.remove("grabbing")});marqueeContainer.addEventListener("mousemove",e=>{if(!isDown)return;e.preventDefault();const x=e.pageX-marqueeContainer.offsetLeft;const walk=(x-startX)*2;marqueeContainer.scrollLeft=scrollLeft-walk});marqueeContainer.addEventListener("wheel",e=>{if(Math.abs(e.deltaX)<Math.abs(e.deltaY)){marqueeContainer.scrollLeft+=e.deltaY;e.preventDefault()}})}
if(!window.YT){const tag=document.createElement("script");tag.src="https://www.youtube.com/iframe_api";document.head.appendChild(tag)}});window.onYouTubeIframeAPIReady=function(){const marquees=document.querySelectorAll(".marquee-boxes-row");let userInteracted=!1;const enableSoundPlayback=()=>{userInteracted=!0;document.removeEventListener("click",enableSoundPlayback);document.removeEventListener("keydown",enableSoundPlayback)};document.addEventListener("click",enableSoundPlayback);document.addEventListener("keydown",enableSoundPlayback);document.querySelectorAll(".video-card").forEach((card)=>{const iframe=card.querySelector(".youtube-iframe");const localVideo=card.querySelector("video");const poster=card.querySelector(".poster");if(localVideo){card.addEventListener("mouseenter",()=>{localVideo.play();marquees.forEach((m)=>(m.style.animationPlayState="paused"))});card.addEventListener("mouseleave",()=>{localVideo.pause();localVideo.currentTime=0;marquees.forEach((m)=>(m.style.animationPlayState="running"))});return}
if(iframe){const player=new YT.Player(iframe,{events:{onReady:(event)=>{card.addEventListener("mouseenter",()=>{if(poster)poster.style.opacity="0";if(userInteracted){event.target.unMute()}else{event.target.mute()}
event.target.playVideo();marquees.forEach((m)=>(m.style.animationPlayState="paused"))});card.addEventListener("mouseleave",()=>{event.target.pauseVideo();if(poster)poster.style.opacity="1";marquees.forEach((m)=>(m.style.animationPlayState="running"))})},},})}})};window.onYouTubeIframeAPIReady=function(){const marquees=document.querySelectorAll(".marquee-boxes-row");let userInteracted=!1;const enableSoundPlayback=()=>{userInteracted=!0;document.removeEventListener("click",enableSoundPlayback);document.removeEventListener("keydown",enableSoundPlayback)};document.addEventListener("click",enableSoundPlayback);document.addEventListener("keydown",enableSoundPlayback);document.querySelectorAll(".video-card").forEach((card)=>{const iframe=card.querySelector(".youtube-iframe");const localVideo=card.querySelector("video");const poster=card.querySelector(".poster");if(localVideo){card.addEventListener("mouseenter",()=>{localVideo.play();marquees.forEach((m)=>(m.style.animationPlayState="paused"))});card.addEventListener("mouseleave",()=>{localVideo.pause();localVideo.currentTime=0;marquees.forEach((m)=>(m.style.animationPlayState="running"))});return}
if(iframe){const player=new YT.Player(iframe,{events:{onReady:(event)=>{card.addEventListener("mouseenter",()=>{if(poster)poster.style.opacity="0";if(userInteracted){event.target.unMute()}else{event.target.mute()}
setTimeout(()=>{event.target.playVideo()},150);marquees.forEach((m)=>(m.style.animationPlayState="paused"))});card.addEventListener("mouseleave",()=>{event.target.pauseVideo();if(poster)poster.style.opacity="1";marquees.forEach((m)=>(m.style.animationPlayState="running"))})},},})}})};document.addEventListener("click",(e)=>{const btn=e.target.closest(".fullscreen-btn");if(!btn)return;const videoCard=btn.closest(".video-card");const iframe=videoCard.querySelector("iframe, video");if(iframe.requestFullscreen){iframe.requestFullscreen()}else if(iframe.webkitRequestFullscreen){iframe.webkitRequestFullscreen()}else if(iframe.msRequestFullscreen){iframe.msRequestFullscreen()}});let userInteracted=!1;document.addEventListener("click",()=>{userInteracted=!0});document.querySelectorAll(".video-card").forEach((card)=>{const iframe=card.querySelector(".youtube-iframe");if(!iframe)return;const player=new YT.Player(iframe,{events:{}});card.addEventListener("mouseenter",()=>{player.playVideo();if(userInteracted){player.unMute()}else{player.mute()}});card.addEventListener("mouseleave",()=>{player.pauseVideo()})});const headingOriginal=document.getElementById("text-marquee-original");const headingClone=document.getElementById("text-marquee-clone");function updateHeadingClone(){if(window.innerWidth>768){headingClone.innerHTML=headingOriginal.innerHTML}else{headingClone.innerHTML=""}}
window.addEventListener("load",updateHeadingClone);window.addEventListener("resize",updateHeadingClone);(function(){emailjs.init({publicKey:"-A-6b9t0YWQYBt5FX"})})();document.getElementById("contact-form").addEventListener("submit",function(e){e.preventDefault();var params={from_name:document.getElementById("name").value,from_email:document.getElementById("email").value,subject:document.getElementById("subject").value,message:document.getElementById("message").value};emailjs.send("service_ucdnwb8","template_c8jc8um",params).then(()=>{alert("✅ Message sent successfully!");document.getElementById("contact-form").reset()}).catch((error)=>{alert("❌ Failed to send message. Check console for details.");console.error("EmailJS Error:",error)})});document.addEventListener("DOMContentLoaded",function(){const filterButtons=document.querySelectorAll(".portfolio-filter");const portfolioItems=document.querySelectorAll(".portfolio-item");filterButtons.forEach((button)=>{button.addEventListener("click",()=>{filterButtons.forEach((btn)=>btn.classList.remove("active"));button.classList.add("active");const filterValue=button.getAttribute("data-filter");portfolioItems.forEach((item)=>{if(filterValue==="all"||item.dataset.category===filterValue){item.style.display="block";item.classList.remove("opacity-0","scale-95");item.classList.add("opacity-100","scale-100")}else{item.classList.add("opacity-0","scale-95");setTimeout(()=>{if(!item.classList.contains("opacity-100")){item.style.display="none"}},300)}})})})});document.addEventListener("DOMContentLoaded",function(){const original=document.getElementById("text-marquee-original");const clone=document.getElementById("text-marquee-clone");clone.innerHTML=original.innerHTML;const totalWidth=original.scrollWidth;clone.style.width=totalWidth+"px"});lucide.createIcons();const counters=document.querySelectorAll('.stat-number');let started=!1;function runCounter(counter){const target=+counter.getAttribute('data-count');const duration=2000;const stepTime=Math.max(Math.floor(duration/target),20);let count=0;const interval=setInterval(()=>{count+=1;counter.textContent=count;if(count>=target)clearInterval(interval);},stepTime)}
function handleScroll(){const section=document.querySelector('.container-section');const sectionTop=section.getBoundingClientRect().top;const windowHeight=window.innerHeight;if(!started&&sectionTop<windowHeight-100){counters.forEach(runCounter);started=!0}}
window.addEventListener('scroll',handleScroll)